// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7s_H6kHd8SSe3jiH9hFuHhACTH_ip3Q',
    appId: '1:36444302462:web:335052eb92450dcfef7c2f',
    messagingSenderId: '36444302462',
    projectId: 'project1-280af',
    authDomain: 'project1-280af.firebaseapp.com',
    storageBucket: 'project1-280af.appspot.com',
    measurementId: 'G-8H0NSDFD71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4VbDPcEEJGvEcJqWG7_muKSpFNHpg728',
    appId: '1:36444302462:android:92319152f81373e7ef7c2f',
    messagingSenderId: '36444302462',
    projectId: 'project1-280af',
    storageBucket: 'project1-280af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKeXeOG_Im_xVkMAJnamTwFEFV4VUBqc',
    appId: '1:36444302462:ios:d5802a84c5357106ef7c2f',
    messagingSenderId: '36444302462',
    projectId: 'project1-280af',
    storageBucket: 'project1-280af.appspot.com',
    iosBundleId: 'com.example.bookMyPlace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKeXeOG_Im_xVkMAJnamTwFEFV4VUBqc',
    appId: '1:36444302462:ios:d5802a84c5357106ef7c2f',
    messagingSenderId: '36444302462',
    projectId: 'project1-280af',
    storageBucket: 'project1-280af.appspot.com',
    iosBundleId: 'com.example.bookMyPlace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU7s_H6kHd8SSe3jiH9hFuHhACTH_ip3Q',
    appId: '1:36444302462:web:e35ac60c0ff071c5ef7c2f',
    messagingSenderId: '36444302462',
    projectId: 'project1-280af',
    authDomain: 'project1-280af.firebaseapp.com',
    storageBucket: 'project1-280af.appspot.com',
    measurementId: 'G-588W5QPTT1',
  );
}
